{
 "title": "Bâtiment RT",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Temperature dans le bâtiment RT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "E004",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "building::tag", "operator": "=", "value": "RT" },
      { "condition": "AND", "key": "room::tag", "operator": "=", "value": "E004" }
     ]
    },
    {
     "alias": "E210",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "building::tag", "operator": "=", "value": "RT" },
      { "condition": "AND", "key": "room::tag", "operator": "=", "value": "E210" }
     ]
    }
   ]
  },
  {
   "title": "10 dernières valeurs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "E004",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "limit": "10",
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "building::tag", "operator": "=", "value": "RT" },
      { "condition": "AND", "key": "room::tag", "operator": "=", "value": "E004" }
     ]
    },
    {
     "alias": "E210",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "limit": "10",
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "building::tag", "operator": "=", "value": "RT" },
      { "condition": "AND", "key": "room::tag", "operator": "=", "value": "E210" }
     ]
    }
   ]
  },
  {
   "title": "CO2 dans le bâtiment RT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "alias": "E004",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "co2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "building::tag", "operator": "=", "value": "RT" },
      { "condition": "AND", "key": "room::tag", "operator": "=", "value": "E004" }
     ]
    },
    {
     "alias": "E210",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "co2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "building::tag", "operator": "=", "value": "RT" },
      { "condition": "AND", "key": "room::tag", "operator": "=", "value": "E210" }
     ]
    }
   ]
  },
  {
   "title": "10 dernières valeurs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "alias": "E004",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "limit": "10",
     "measurement": "co2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "building::tag", "operator": "=", "value": "RT" },
      { "condition": "AND", "key": "room::tag", "operator": "=", "value": "E004" }
     ]
    },
    {
     "alias": "E210",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "limit": "10",
     "measurement": "co2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "building::tag", "operator": "=", "value": "RT" },
      { "condition": "AND", "key": "room::tag", "operator": "=", "value": "E210" }
     ]
    }
   ]
  },
  {
   "title": "Humidité dans le bâtiment RT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "alias": "E004",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "building::tag", "operator": "=", "value": "RT" },
      { "condition": "AND", "key": "room::tag", "operator": "=", "value": "E004" }
     ]
    },
    {
     "alias": "E210",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "building::tag", "operator": "=", "value": "RT" },
      { "condition": "AND", "key": "room::tag", "operator": "=", "value": "E210" }
     ]
    }
   ]
  },
  {
   "title": "10 dernières valeurs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "alias": "E004",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "limit": "10",
     "measurement": "humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "building::tag", "operator": "=", "value": "RT" },
      { "condition": "AND", "key": "room::tag", "operator": "=", "value": "E004" }
     ]
    },
    {
     "alias": "E210",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "limit": "10",
     "measurement": "humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "building::tag", "operator": "=", "value": "RT" },
      { "condition": "AND", "key": "room::tag", "operator": "=", "value": "E210" }
     ]
    }
   ]
  }
 ]
}